plugins {
    id 'java'
    id 'jacoco'
    id 'org.springframework.boot' version '4.0.7'
    id 'io.spring.dependency-management' version '1.1.7'
    id 'com.github.davidmc24.gradle.plugin.avro' version '1.9.1'
}

group = 'com.example'
version = '0.1.0'

// Configure the fat JAR (default behavior of Spring Boot)
jar.enabled = false
bootJar {
    archiveBaseName = "${project.name}"
    archiveVersion = "${project.version}"
}


java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

compileJava.dependsOn generateAvroJava

sourceSets {
    main {
        java {
            srcDir 'build/generated-main-avro-java'
        }
    }
}


configurations {
    compileOnly {
        extendsFrom annotationProcessor
    }
}

repositories {
    mavenCentral()
    maven {
        url 'https://packages.confluent.io/maven'   // Add this for Confluent artifacts
    }
}


dependencies {
    // Spring Boot starters
    implementation 'org.springframework.boot:spring-boot-starter-kafka'
    testImplementation 'org.springframework.kafka:spring-kafka-test'

    // Avro dependencies
    implementation 'org.apache.avro:avro:1.12.1'
    implementation 'io.confluent:kafka-avro-serializer:8.2.0'
    implementation 'io.confluent:kafka-schema-registry-client:8.2.0'

    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'

    testImplementation 'org.mockito:mockito-core:5.23.0'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'org.springframework.kafka:spring-kafka-test'
    testImplementation 'org.springframework.integration:spring-integration-test'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

    // faker
    implementation 'net.datafaker:datafaker:2.5.4'


}


tasks.named('test') {
    useJUnitPlatform()
}

def jacocoExcludes = [
        '**/dto/**',
        'com/example/springkafka/config/*',
        '**/exception/**',
        '**/*Config*',
]

tasks.test {
    finalizedBy jacocoTestReport  // ensure report after test
}

jacocoTestReport {
    reports {
        html.required = true
        xml.required = false
        csv.required = false
        html.outputLocation = layout.buildDirectory.dir("reports/jacoco/html")
    }
    dependsOn test
}

jacocoTestCoverageVerification {
    violationRules {
        rule {
            limit {
                minimum = 0.50
            }
            excludes = jacocoExcludes
        }
    }
    dependsOn jacocoTestReport
    shouldRunAfter jacocoTestReport
}

check.dependsOn jacocoTestCoverageVerification





// integration tests
sourceSets {
    integrationTest {
        java {
            srcDir 'src/integrationTest/java'
        }
        resources {
            srcDir 'src/integrationTest/resources'
        }
        compileClasspath += main.output + test.output
        runtimeClasspath += main.output + test.output
    }
}

// Let integrationTest configuration extend from testImplementation / testRuntimeOnly
configurations {
    integrationTestImplementation.extendsFrom(testImplementation)
    integrationTestRuntimeOnly.extendsFrom(testRuntimeOnly)
}

tasks.register('integrationTest', Test) {
    description = 'Runs integration tests.'
    group = 'verification'

    testClassesDirs = sourceSets.integrationTest.output.classesDirs
    classpath = sourceSets.integrationTest.runtimeClasspath

    testLogging {
        events "failed"     //  "passed", "skipped"
    }
    // you may want integration tests to run after unit tests
    shouldRunAfter test

    // use JUnit 5
    useJUnitPlatform()
}

check.dependsOn integrationTest
