spring:
  application:
    name: SpringKafka


  kafka:
    bootstrap-servers: 192.168.1.71:9092
    streams:
      application-id: my-streams-app
      # default serdes:
      properties:
        default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
        default.value.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
        schema.registry.url: http://192.168.1.71:8081



#logging:
#  level:
#    root: debug



server:
  servlet:
    context-path: /v1/kafka


logging:
  file:
    name: /tmp/spring/${spring.application.name}.log

  level:
    file: debug





