

spring:
  #  # spring kafka config
  kafka:
    bootstrap-servers: kafka-aiven-68f0cd7-duoley-9bac.i.aivencloud.com:24982
    producer:
      acks: all
      client-id: spring-kafka-producer-group-1
      security:
        protocol: SSL


    consumer:
      group-id: spring-kafka-consumer-group-1

    listener:
      log-container-config: true

    schema-registry-url: 'https://kafka-aiven-68f0cd7-duoley-9bac.i.aivencloud.com:24985'

    security:
      protocol: SSL

logging:
#  level:
#    org.springframework.kafka: debug

kafka:
  producer:
    enabled: false


