spring:
  application:
    name: SpringKafka


  #  # spring kafka config
  kafka:
    bootstrap-servers: kafka.broker.local:9092,192.168.1.71:9092
    #    producer:
    #      acks: all
    #
    #      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    #      key-serializer: org.apache.kafka.common.serialization.StringSerializer
    #      client-id: spring-kafka-producer-client

    consumer:
      #      client-id: spring-kafka-consumer-client
      #      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      #      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: spring-kafka-consumer-group-1

    listener:
      log-container-config: true



server:
  servlet:
    context-path: /v1/kafka



logging:
#  level:
#    org.springframework.kafka: debug

kafka:
  producer:
    enabled: false


